import { ActorDetails } from '../../shared/models/actor-details';

export const mockGetActor: ActorDetails = {
    adult: false,
    also_known_as: [
        'James Edmund Caan ',
        'Jimmy Caan',
        'Джеймс Каан',
        '詹姆斯·凯恩',
    ],
    biography:
        'James Langston Edmund Caan (Nova Iorque, 26 de março de 1940 – Los Angeles, 6 de julho de 2022) foi um ator americano, conhecido pelo papel de Sonny Corleone no clássico de Francis Ford Coppola "O Poderoso Chefão" de 1972, e por seus trabalhos em "El Dorado" (1966) de Howard Hawks onde fez o papel de Alan Bourdillion Traherne chamado Mississippi, ao lado de John Wayne, Rollerball (1975), e Misery (1990). Com uma carreira de grande ascendência, James Caan participou em variados filmes. Em 1996 fez o papel de Robert Deguerin, no filme Eraser, filme estrelado por Arnold Schwarzenegger.',
    birthday: '1940-03-26',
    deathday: '2022-07-06',
    gender: 2,
    homepage: undefined,
    id: 3085,
    imdb_id: 'nm0001001',
    known_for_department: 'Acting',
    name: 'James Caan',
    place_of_birth: 'The Bronx, New York, USA',
    popularity: 53.047,
    profile_path: '/bGyOCCOIgcIyKjOGLoXoyp0XWHf.jpg',
    movie_credits: {
        cast: [
            {
                adult: false,
                backdrop_path: '/cgo3OmF84touDrrLkQ1DQ3MRFyO.jpg',
                genre_ids: [18, 53],
                id: 1700,
                original_language: 'en',
                original_title: 'Misery',
                overview:
                    'Depois de terminar seu mais novo manuscrito, o escritor de sucesso, Paul Sheldon, decide sair para comemorar. O problema é que está nevando demais e Paul acaba sofrendo um terrível acidente. Ele é salvo e abrigado por uma ex-enfermeira chamada Annie Wilkes, que se auto-intitula sua fã número um. Aparentemente uma simpática e doce senhora, Annie, aos poucos, vai se revelando uma sádica psicótica, que começa a torturar Paul quando descobre que ele matou sua personagem favorita em seu último livro publicado. Agora, Paul Sheldon terá de usar suas artimanhas de escritor para ganhar tempo, enganar Annie e, com sorte, escapar deste pesadelo.',
                popularity: 24.301,
                poster_path: '/3aANzopHLOlJLrq9LfbJI5zY2IP.jpg',
                release_date: '1990-11-30',
                title: 'Louca Obsessão',
                video: false,
                vote_average: 7.755,
                vote_count: 4342,
                character: 'Paul Sheldon',
                credit_id: '52fe430ec3a36847f8037015',
                order: 0,
            },
            {
                adult: false,
                backdrop_path: '/ukFD3W0OkGQiA4qfQewAVL3WgRb.jpg',
                genre_ids: [10770, 80, 9648],
                id: 1848,
                original_language: 'en',
                original_title: 'Poodle Springs',
                overview: '',
                popularity: 3.903,
                poster_path: '/ySroOZG9J50vMlKTc4fwyiOxmxR.jpg',
                release_date: '1998-07-25',
                title: 'Poodle Springs',
                video: false,
                vote_average: 5.559,
                vote_count: 17,
                character: 'Philip Marlowe',
                credit_id: '52fe431ac3a36847f803a739',
                order: 0,
            },
            {
                adult: false,
                backdrop_path: '/npNbRiUGU29nz464ERJiAkxH997.jpg',
                genre_ids: [878, 80, 53],
                id: 10128,
                original_language: 'en',
                original_title: 'Alien Nation',
                overview:
                    'No deserto de Mojave, Califórnia, uma pane na nave espacial obriga 300 mil humanóides a conviver com os humanos. Uma dupla de detetives diferentes - um terráqueo, e outro vindo do espaço - precisa superar as hostilidades e investigar um crime.',
                popularity: 13.208,
                poster_path: '/r1blhrOgBYaxZRIjqlNPf6rGHvN.jpg',
                release_date: '1988-10-07',
                title: 'Missão Alien',
                video: false,
                vote_average: 6.056,
                vote_count: 278,
                character: 'Det. Sgt. Matthew Sykes',
                credit_id: '52fe432f9251416c75006b9d',
                order: 0,
            },
            {
                adult: false,
                backdrop_path: '/1JwLeunKPVPgcP2HpGWiAPvNlMN.jpg',
                genre_ids: [28, 878],
                id: 11484,
                original_language: 'en',
                original_title: 'Rollerball',
                overview:
                    'Em uma sociedade futurista, as corporações têm substituído países e existe um jogo recreativo e violento conhecido como"Rollerball", o qual é controlado pelas organizações e jogado em todo o mundo. Em um determinado momento, Jonathan E., um dos jogadores, decide lutar por sua liberdade e deixa o controle da corporação em perigo.',
                popularity: 18.43,
                poster_path: '/xGlUI9aTDGkY9BTeAFB3nEZecY2.jpg',
                release_date: '1975-06-25',
                title: 'Rollerball: Os Gladiadores do Futuro',
                video: false,
                vote_average: 6.225,
                vote_count: 483,
                character: 'Jonathan E.',
                credit_id: '52fe44499251416c7502f69f',
                order: 0,
            },
            {
                adult: false,
                backdrop_path: '/3pYudqkEC8rkjqpBw8pqoLUtGHe.jpg',
                genre_ids: [80, 53, 28],
                id: 11524,
                original_language: 'en',
                original_title: 'Thief',
                overview:
                    'Frank é um especialista em crimes com cofres e pedras preciosas e após ficar preso algum tempo, decide dar novo rumo a sua vida. Casa, família e trabalho estão em seus planos. Até que um chefe do crime lhe envolve em um último crime, que lhe dará o dinheiro para iniciar sua nova vida.',
                popularity: 12.383,
                poster_path: '/vu0CEvqH3pKN2nIrvDISJJiuDok.jpg',
                release_date: '1981-03-27',
                title: 'Profissão: Ladrão',
                video: false,
                vote_average: 7.168,
                vote_count: 607,
                character: 'Frank',
                credit_id: '52fe44529251416c7503094f',
                order: 0,
            },
        ],
        crew: [
            {
                adult: false,
                backdrop_path: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
                genre_ids: [18, 80],
                id: 240,
                original_language: 'en',
                original_title: 'The Godfather Part II',
                overview:
                    'Após a máfia matar sua família, o jovem Vito foge da sua cidade na Sicília e vai para a América. Vito luta para manter sua família. Ele mata Black Hand Fanucci, que exigia dos comerciantes uma parte dos seus ganhos. Com a morte de Fanucci, o poderio de Vito cresce, mas sua família é o que mais importa para ele. Agora baseado no Lago Tahoe, Michael planeja fazer incursões em Las Vegas e Havana instalando negócios ligados ao lazer, mas descobre que aliados como Hyman Roth estão tentando matá-lo.',
                popularity: 66.949,
                poster_path: '/7g6wvsWHxBQujUcSXvZLhdFpDUy.jpg',
                release_date: '1974-12-20',
                title: 'O Poderoso Chefão: Parte II',
                video: false,
                vote_average: 8.6,
                vote_count: 11791,
                credit_id: '57472235c3a36839df000077',
                department: 'Crew',
                job: 'Thanks',
            },
            {
                adult: false,
                backdrop_path: '/6iQrSNGKQt4Qm2EJTJYEDf2zX6l.jpg',
                genre_ids: [18],
                id: 48949,
                original_language: 'en',
                original_title: 'Hide in Plain Sight',
                overview: '',
                popularity: 4.325,
                poster_path: '/eIflB83WrFjtlMbxJxodGgeV5Oz.jpg',
                release_date: '1980-03-21',
                title: 'Hide in Plain Sight',
                video: false,
                vote_average: 5.3,
                vote_count: 15,
                credit_id: '52fe477cc3a36847f813874f',
                department: 'Directing',
                job: 'Director',
            },
        ],
    },
};
