import { MovieDetails } from '../../shared/models/movie-details';

export const mockGetMovie: MovieDetails = {
    adult: false,
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    belongs_to_collection: {
        id: 230,
        name: 'O Poderoso Chefão: Coleção',
        poster_path: '/s4i9pFeUj4gSJaA487kjq9ePJrR.jpg',
        backdrop_path: '/mDMCET9Ens5ANvZAWRpluBsMAtS.jpg',
    },
    budget: 6000000,
    genres: [
        {
            id: 18,
            name: 'Drama',
        },
        {
            id: 80,
            name: 'Crime',
        },
    ],
    homepage: '',
    id: 238,
    imdb_id: 'tt0068646',
    original_language: 'en',
    original_title: 'The Godfather',
    overview:
        'Em 1945, Don Corleone é o chefe de uma mafiosa família italiana de Nova York. Ele costuma apadrinhar várias pessoas, realizando importantes favores para elas, em troca de favores futuros. Com a chegada das drogas, as famílias começam uma disputa pelo promissor mercado. Quando Corleone se recusa a facilitar a entrada dos narcóticos na cidade, não oferecendo ajuda política e policial, sua família começa a sofrer atentados para que mudem de posição. É nessa complicada época que Michael, um herói de guerra nunca envolvido nos negócios da família, vê a necessidade de proteger o seu pai e tudo o que ele construiu ao longo dos anos.',
    popularity: 110.668,
    poster_path: '/oJagOzBu9Rdd9BrciseCm3U3MCU.jpg',
    production_companies: [
        {
            id: 4,
            logo_path: '/gz66EfNoYPqHTYI4q9UEN4CbHRc.png',
            name: 'Paramount',
            origin_country: 'US',
        },
        {
            id: 5,
            logo_path: '/mock2.png',
            name: 'Mock2',
            origin_country: 'US',
        },
    ],
    production_countries: [
        {
            iso_3166_1: 'US',
            name: 'United States of America',
        },
    ],
    release_date: '1972-03-14',
    revenue: 245066411,
    runtime: 175,
    spoken_languages: [
        {
            english_name: 'English',
            iso_639_1: 'en',
            name: 'English',
        },
        {
            english_name: 'Italian',
            iso_639_1: 'it',
            name: 'Italiano',
        },
        {
            english_name: 'Latin',
            iso_639_1: 'la',
            name: 'Latin',
        },
    ],
    status: 'Released',
    tagline: 'Uma oferta que você não vai poder recusar.',
    title: 'O Poderoso Chefão',
    video: false,
    vote_average: 8.695,
    vote_count: 19520,
    credits: {
        cast: [
            {
                adult: false,
                gender: 2,
                id: 3084,
                known_for_department: 'Acting',
                name: 'Marlon Brando',
                original_name: 'Marlon Brando',
                popularity: 21.017,
                profile_path: '/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg',
                cast_id: 146,
                character: 'Don Vito Corleone',
                credit_id: '6489aa85e2726001072483a9',
                order: 0,
            },
            {
                adult: false,
                gender: 2,
                id: 1158,
                known_for_department: 'Acting',
                name: 'Al Pacino',
                original_name: 'Al Pacino',
                popularity: 44.081,
                profile_path: '/2dGBb1fOcNdZjtQToVPFxXjm4ke.jpg',
                cast_id: 147,
                character: 'Michael Corleone',
                credit_id: '6489aa936f8d9500afdf219c',
                order: 1,
            },
            {
                adult: false,
                gender: 2,
                id: 3085,
                known_for_department: 'Acting',
                name: 'James Caan',
                original_name: 'James Caan',
                popularity: 53.047,
                profile_path: '/bGyOCCOIgcIyKjOGLoXoyp0XWHf.jpg',
                cast_id: 148,
                character: 'Sonny Corleone',
                credit_id: '6489aabc99259c00ff111136',
                order: 2,
            },
            {
                adult: false,
                gender: 2,
                id: 3087,
                known_for_department: 'Acting',
                name: 'Robert Duvall',
                original_name: 'Robert Duvall',
                popularity: 32.973,
                profile_path: '/3tcKxC5Sc3DJ6XPDKKC2EAomEWn.jpg',
                cast_id: 149,
                character: 'Tom Hagen',
                credit_id: '6489aace99259c011c42808d',
                order: 3,
            },
            {
                adult: false,
                gender: 2,
                id: 3086,
                known_for_department: 'Acting',
                name: 'Richard S. Castellano',
                original_name: 'Richard S. Castellano',
                popularity: 23.115,
                profile_path: '/1vr75BdHWret81vuSJ3ugiCBkxw.jpg',
                cast_id: 150,
                character: 'Clemenza',
                credit_id: '6489aaf86f8d9500c88bea14',
                order: 4,
            },
        ],
        crew: [
            {
                adult: false,
                gender: 2,
                id: 154,
                known_for_department: 'Editing',
                name: 'Walter Murch',
                original_name: 'Walter Murch',
                popularity: 12.49,
                profile_path: '/kQh7U7kRLF9NKEMpxiGjZEIu0o3.jpg',
                credit_id: '62bd43fb63d9370092ba09da',
                department: 'Crew',
                job: 'Post Production Consulting',
            },
            {
                adult: false,
                gender: 2,
                id: 1776,
                known_for_department: 'Directing',
                name: 'Francis Ford Coppola',
                original_name: 'Francis Ford Coppola',
                popularity: 24.248,
                profile_path: '/3Pblihd6KjXliie9vj4iQJwbNPU.jpg',
                credit_id: '52fe422bc3a36847f80093db',
                department: 'Writing',
                job: 'Screenplay',
            },
            {
                adult: false,
                gender: 2,
                id: 1776,
                known_for_department: 'Directing',
                name: 'Francis Ford Coppola',
                original_name: 'Francis Ford Coppola',
                popularity: 24.248,
                profile_path: '/3Pblihd6KjXliie9vj4iQJwbNPU.jpg',
                credit_id: '5e92505cccb15f00136de455',
                department: 'Directing',
                job: 'Director',
            },
            {
                adult: false,
                gender: 2,
                id: 2871,
                known_for_department: 'Production',
                name: 'Fred Roos',
                original_name: 'Fred Roos',
                popularity: 6.607,
                profile_path: '/qfXLY5E589l0TQnoayWmUrBDsgo.jpg',
                credit_id: '53885041c3a3681ad700459b',
                department: 'Production',
                job: 'Casting',
            },
            {
                adult: false,
                gender: 2,
                id: 2872,
                known_for_department: 'Sound',
                name: 'Carmine Coppola',
                original_name: 'Carmine Coppola',
                popularity: 3.923,
                profile_path: '/iURpKXIgdtQoVCBQ8GKGvb0Qw5z.jpg',
                credit_id: '62bd43877304b52384a221cb',
                department: 'Crew',
                job: 'Additional Music',
            },
        ],
    },
    videos: {
        results: [
            {
                iso_639_1: 'pt',
                iso_3166_1: 'BR',
                name: 'O Poderoso Chefão | Aniversário de 50 Anos | Trailer Oficial | Paramount Pictures Brasil',
                key: '0v6MO0EB7UY',
                site: 'YouTube',
                size: 1080,
                type: 'Trailer',
                official: true,
                published_at: '2022-01-13T14:03:27.000Z',
                id: '623a98c2e942be00877e6683',
            },
        ],
    },
    release_dates: {
        results: [
            {
                iso_3166_1: 'AR',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '2011-11-24T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'AU',
                release_dates: [
                    {
                        certification: 'MA 15+',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-11-02T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'BR',
                release_dates: [
                    {
                        certification: '14',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-07-07T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '14',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'DVD/VHS',
                        release_date: '2000-12-07T00:00:00.000Z',
                        type: 5,
                    },
                    {
                        certification: '14',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'DVD/VHS',
                        release_date: '2008-04-29T00:00:00.000Z',
                        type: 5,
                    },
                ],
            },
            {
                iso_3166_1: 'CA',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-03-14T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'CZ',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1994-09-01T00:00:00.000Z',
                        type: 5,
                    },
                ],
            },
            {
                iso_3166_1: 'DE',
                release_dates: [
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-08-24T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'DVD',
                        release_date: '2001-07-22T00:00:00.000Z',
                        type: 5,
                    },
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'Blu-ray',
                        release_date: '2008-10-06T00:00:00.000Z',
                        type: 5,
                    },
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'Ultra HD Blu-ray',
                        release_date: '2022-03-24T00:00:00.000Z',
                        type: 5,
                    },
                ],
            },
            {
                iso_3166_1: 'DK',
                release_dates: [
                    {
                        certification: '15',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-12-26T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'EE',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '50th Anniversary Edition',
                        release_date: '2022-03-14T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'ES',
                release_dates: [
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-10-20T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'FI',
                release_dates: [
                    {
                        certification: 'K-18',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-09-29T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'FR',
                release_dates: [
                    {
                        certification: '12',
                        descriptors: [],
                        iso_639_1: '',
                        note: '50th anniversary re-release, restoration.',
                        release_date: '2022-02-25T00:00:00.000Z',
                        type: 2,
                    },
                    {
                        certification: '12',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-03-15T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'VOD',
                        release_date: '2017-12-27T00:00:00.000Z',
                        type: 4,
                    },
                    {
                        certification: '18',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'Prime Video',
                        release_date: '2022-07-22T00:00:00.000Z',
                        type: 4,
                    },
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'DVD',
                        release_date: '2004-06-10T00:00:00.000Z',
                        type: 5,
                    },
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'Blu-Ray',
                        release_date: '2010-06-15T00:00:00.000Z',
                        type: 5,
                    },
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'VHS',
                        release_date: '1997-11-20T00:00:00.000Z',
                        type: 5,
                    },
                ],
            },
            {
                iso_3166_1: 'GB',
                release_dates: [
                    {
                        certification: '15',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-08-24T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '18',
                        descriptors: [],
                        iso_639_1: 'en',
                        note: '',
                        release_date: '2001-10-09T00:00:00.000Z',
                        type: 5,
                    },
                ],
            },
            {
                iso_3166_1: 'GR',
                release_dates: [
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-09-29T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'Re-issue',
                        release_date: '2023-10-26T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '2016-06-30T00:00:00.000Z',
                        type: 4,
                    },
                ],
            },
            {
                iso_3166_1: 'HK',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1980-01-24T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'HU',
                release_dates: [
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1982-03-25T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'IE',
                release_dates: [
                    {
                        certification: '18',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-08-25T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'IT',
                release_dates: [
                    {
                        certification: 'T',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-09-21T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'JP',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '2016-06-30T00:00:00.000Z',
                        type: 2,
                    },
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '2004-06-19T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-07-15T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'KR',
                release_dates: [
                    {
                        certification: '18',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-12-27T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'MX',
                release_dates: [
                    {
                        certification: 'C',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1998-08-14T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'NL',
                release_dates: [
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1973-01-18T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'Re-release',
                        release_date: '2011-11-10T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'Blu ray',
                        release_date: '2012-06-27T00:00:00.000Z',
                        type: 5,
                    },
                    {
                        certification: '16',
                        descriptors: [],
                        iso_639_1: '',
                        note: 'DVD',
                        release_date: '2008-01-14T00:00:00.000Z',
                        type: 5,
                    },
                ],
            },
            {
                iso_3166_1: 'NO',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-10-16T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'PT',
                release_dates: [
                    {
                        certification: 'M/18',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-10-24T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'SE',
                release_dates: [
                    {
                        certification: '15',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-09-27T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'SG',
                release_dates: [
                    {
                        certification: 'M18',
                        descriptors: [],
                        iso_639_1: '',
                        note: 're-release',
                        release_date: '2022-02-25T00:00:00.000Z',
                        type: 2,
                    },
                ],
            },
            {
                iso_3166_1: 'TH',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '2022-02-25T00:00:00.000Z',
                        type: 2,
                    },
                ],
            },
            {
                iso_3166_1: 'TR',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1973-10-19T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
            {
                iso_3166_1: 'US',
                release_dates: [
                    {
                        certification: 'R',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-03-14T00:00:00.000Z',
                        type: 1,
                    },
                    {
                        certification: 'R',
                        descriptors: [],
                        iso_639_1: '',
                        note: '50th Anniversary Edition',
                        release_date: '2022-02-25T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: 'R',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-03-24T00:00:00.000Z',
                        type: 3,
                    },
                    {
                        certification: 'R',
                        descriptors: [],
                        iso_639_1: '',
                        note: '4K UHD',
                        release_date: '2022-03-22T00:00:00.000Z',
                        type: 5,
                    },
                ],
            },
            {
                iso_3166_1: 'UY',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '1972-08-10T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
        ],
    },
};
