import { Actor } from '../../models/actor';

export const mockTitle: string = 'Atores';
export const mockActors: Actor[] = [
    {
        adult: false,
        gender: 2,
        id: 976,
        known_for_department: 'Acting',
        name: 'Jason Statham',
        original_name: 'Jason Statham',
        popularity: 377.015,
        profile_path: '/lldeQ91GwIVff43JBrpdbAAeYWj.jpg',
        known_for: [
            {
                adult: false,
                backdrop_path: '/2uSCHUsmzb6KkQPFSxBQ7bgfJLE.jpg',
                id: 345940,
                title: 'Megatubarão',
                original_language: 'en',
                original_title: 'The Meg',
                overview:
                    'Na fossa mais profunda do Oceano Pacífico, a tripulação de um submarino fica presa dentro do local após ser atacada por uma criatura pré-histórica que se achava estar extinta, um tubarão de mais de 20 metros de comprimento, o Megalodon. Para salvá-los, um oceanógrafo chinês contrata Jonas Taylor, um mergulhador especializado em resgates em água profundas que já encontrou com a criatura anteriormente.',
                poster_path: '/wrJkShDPK4TcV0nHix3HASEmkul.jpg',
                media_type: 'movie',
                genre_ids: [28, 878, 27],
                popularity: 65.025,
                release_date: '2018-08-09',
                video: false,
                vote_average: 6.256,
                vote_count: 7306,
            },
            {
                adult: false,
                backdrop_path: '/kWt1OcPgwO1ssu57wgTKmq38JYw.jpg',
                id: 4108,
                title: 'Carga Explosiva',
                original_language: 'en',
                original_title: 'The Transporter',
                overview:
                    'O ex-operador das Forças Especiais Frank Martin vive o que parece ser uma vida tranquila ao longo do Mediterrâneo francês. Na verdade ele é um transportador mercenário levando bens, humanos ou não, de um lugar para outro, sem fazer perguntas sobre que tipo de mercadoria foi contratado para transportar.',
                poster_path: '/iajTcyco5MEscLp0ue59lVY2WtH.jpg',
                media_type: 'movie',
                genre_ids: [28, 80, 53],
                popularity: 45.416,
                release_date: '2002-10-02',
                video: false,
                vote_average: 6.701,
                vote_count: 5065,
            },
            {
                adult: false,
                backdrop_path: '/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg',
                id: 337339,
                title: 'Velozes \u0026 Furiosos 8',
                original_language: 'en',
                original_title: 'The Fate of the Furious',
                overview:
                    'Depois que Brian e Mia se aposentaram, e o resto da equipe foi exonerado, Dom e Letty estão em lua de mel e levam uma vida pacata e completamente normal. Mas a adrenalina do passado volta com tudo quando uma mulher misteriosa faz com que Dom retorne ao mundo do crime e da velocidade.',
                poster_path: '/38RVo4cX1O7Ia6k9WXcxkxprHm.jpg',
                media_type: 'movie',
                genre_ids: [28, 80, 53],
                popularity: 59.154,
                release_date: '2017-04-12',
                video: false,
                vote_average: 6.882,
                vote_count: 9944,
            },
        ],
    },
    {
        adult: false,
        gender: 1,
        id: 115440,
        known_for_department: 'Acting',
        name: 'Sydney Sweeney',
        original_name: 'Sydney Sweeney',
        popularity: 204.397,
        profile_path: '/qYiaSl0Eb7G3VaxOg8PxExCFwon.jpg',
        known_for: [
            {
                adult: false,
                backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
                id: 1072790,
                title: 'Todos Menos Você',
                original_language: 'en',
                original_title: 'Anyone But You',
                overview:
                    'Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.',
                poster_path: '/tPx1HEiS5zd9mLvtb52YY66dkEO.jpg',
                media_type: 'movie',
                genre_ids: [35, 10749],
                popularity: 932.844,
                release_date: '2023-12-21',
                video: false,
                vote_average: 6.975,
                vote_count: 855,
            },
            {
                adult: false,
                backdrop_path: '/3rwszCm4XyBtIWSjbUbgNwJOidu.jpg',
                id: 645710,
                title: 'Observadores',
                original_language: 'en',
                original_title: 'The Voyeurs',
                overview:
                    'Depois de se mudarem para um lindo apartamento no centro de Montreal, um jovem casal começa a se interessar cada vez mais pela vida sexual de seus vizinhos excêntricos do outro lado da rua. O que começa como uma curiosidade inocente aos poucos se transforma em uma obsessão doentia, depois que descobrem que um dos vizinhos está traindo o outro. A tentação e o desejo fazem com que suas vidas se enredem de maneiras inesperadas, levando a consequências mortais.',
                poster_path: '/bOFs0xHCOSTvIUYL0LDd5qcuuDB.jpg',
                media_type: 'movie',
                genre_ids: [53],
                popularity: 36.549,
                release_date: '2021-08-25',
                video: false,
                vote_average: 6.646,
                vote_count: 767,
            },
        ],
    },
    {
        adult: false,
        gender: 2,
        id: 12799,
        known_for_department: 'Acting',
        name: 'Jeremy Piven',
        original_name: 'Jeremy Piven',
        popularity: 197.269,
        profile_path: '/pqdR8zqAWF87chGYlbdYr0YfC7g.jpg',
        known_for: [
            {
                adult: false,
                backdrop_path: '/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg',
                id: 920,
                title: 'Carros',
                original_language: 'en',
                original_title: 'Cars',
                overview:
                    'Ao viajar para a Califórnia, o famoso carro de corridas Relâmpago McQueen se perde e vai parar em Radiator Springs, uma cidadezinha na Rota 66. Ele conhece novos amigos e aprende lições que mudam sua forma de encarar a vida.',
                poster_path: '/2nM2NRV8wt3n3ffoHQ3KdMkY3vR.jpg',
                media_type: 'movie',
                genre_ids: [16, 12, 35, 10751],
                popularity: 56.947,
                release_date: '2006-06-08',
                video: false,
                vote_average: 6.956,
                vote_count: 13306,
            },
            {
                adult: false,
                backdrop_path: '/rqpPH5At8AzYUYR2GneC0x65GeK.jpg',
                id: 9778,
                title: 'Escrito nas Estrelas',
                original_language: 'en',
                original_title: 'Serendipity',
                overview:
                    'Num apressado dia de compras no inverno de 1990, Jonathan Trager (John Cusack) conhece Sara Thomas (Kate Beckinsale). Dois estranhos no meio da massa em NY, seus caminhos se cruzam em um feriado, sendo que logo sentem entre eles uma atração mútua. Apesar do fato de ambos estarem envolvidos em outras relações, Jonathan e Sara passam a noite andando por Manhattan. Quando a noite chega ao fim, os dois são forçados a determinar algo como seu próximo passo. Quando Jonathan sugere uma troca de telefones, Sara rejeita e propõe uma idéia que dará ao destino o controle de seu futuro. Se eles tiverem que ficar juntos, ela diz a ele, eles encontrarão o caminho de volta para a vida um do outro.',
                poster_path: '/kD0U1dENdFpbTm6cIWIkZOqKMkB.jpg',
                media_type: 'movie',
                genre_ids: [35, 10749, 18],
                popularity: 19.736,
                release_date: '2001-10-05',
                video: false,
                vote_average: 6.9,
                vote_count: 1813,
            },
            {
                adult: false,
                backdrop_path: '/6bNQuKFJIamipvYclG4MEbDSLM5.jpg',
                id: 93837,
                title: 'A Super Agente',
                original_language: 'en',
                original_title: 'So Undercover',
                overview:
                    'Estrelado por Miley Cyrus, Molly Moris, uma investigadora particular que resolve deixar a escola para trabalhar com o seu pai, um ex-policial. Juntos, seus dias são preenchidos com flagrantes de traição e pequenos roubos. No entanto, sua vida muda quando inesperadamente ela é abordada por um agente do FBI que a contrata para ficar disfarçada em um lugar que eles são incapazes de se infiltrar, um mundo do qual ela não entende nada... A vida de universitária.',
                poster_path: '/sMMVRr7vCxoZnNIdiRheBWPAJ6c.jpg',
                media_type: 'movie',
                genre_ids: [28, 35],
                popularity: 18.026,
                release_date: '2012-12-06',
                video: false,
                vote_average: 6.2,
                vote_count: 1091,
            },
        ],
    },
    {
        adult: false,
        gender: 1,
        id: 933238,
        known_for_department: 'Acting',
        name: 'Rebecca Ferguson',
        original_name: 'Rebecca Ferguson',
        popularity: 176.89,
        profile_path: '/lJloTOheuQSirSLXNA3JHsrMNfH.jpg',
        known_for: [
            {
                adult: false,
                backdrop_path: '/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg',
                id: 438631,
                title: 'Duna',
                original_language: 'en',
                original_title: 'Dune',
                overview:
                    'Em um futuro distante, planetas são comandados por casas nobres que fazem parte de um império feudal intergalático. Paul Atreides é um jovem cuja família toma o controle do planeta deserto Arrakis, também conhecido como Duna. A única fonte da especiaria Melange, a substância mais importante do cosmos, Arrakis se mostra ser um planeta nem um pouco fácil de governar.',
                poster_path: '/eLXRCSKXAo9831a9Bw22TdZSnzL.jpg',
                media_type: 'movie',
                genre_ids: [878, 12],
                popularity: 738.715,
                release_date: '2021-09-15',
                video: false,
                vote_average: 7.789,
                vote_count: 10552,
            },
            {
                adult: false,
                backdrop_path: '/4SO6pbGJTpM9YYovYxFLY3MXqZn.jpg',
                id: 346685,
                title: 'A Garota no Trem',
                original_language: 'en',
                original_title: 'The Girl on the Train',
                overview:
                    'Rachel, uma alcoólatra desempregada e deprimida, sofre pelo seu divórcio recente. Todas as manhãs ela viaja de trem de Ashbury a Londres, fantasiando sobre a vida de um jovem casal que vigia pela janela. Certo dia ela testemunha uma cena chocante e mais tarde descobre que a mulher está desaparecida. Inquieta, Rachel recorre a polícia e se vê completamente envolvida no mistério.',
                poster_path: '/AktZTeympJEIK2QgyB29IiWfCI8.jpg',
                media_type: 'movie',
                genre_ids: [53, 9648, 18, 80],
                popularity: 24.397,
                release_date: '2016-10-05',
                video: false,
                vote_average: 6.435,
                vote_count: 5524,
            },
            {
                adult: false,
                backdrop_path: '/nNh7vHHISVAaziJEqAq0P9iL52w.jpg',
                id: 395992,
                title: 'Vida',
                original_language: 'en',
                original_title: 'Life',
                overview:
                    'Um time de cientistas a bordo da Estação Espacial Internacional cuja missão de descoberta se transforma em medo puro quando eles encontram uma forma de vida em desenvolvimento que causou a extinção da vida em Marte e agora ameaça a tripulação e a vida na Terra.',
                poster_path: '/bKacW7BlSPHYvklyhSHvJrNl1CO.jpg',
                media_type: 'movie',
                genre_ids: [27, 878, 9648, 53],
                popularity: 47.205,
                release_date: '2017-03-22',
                video: false,
                vote_average: 6.435,
                vote_count: 7008,
            },
        ],
    },
    {
        adult: false,
        gender: 1,
        id: 1434487,
        known_for_department: 'Acting',
        name: 'Anna Sawai',
        original_name: 'Anna Sawai',
        popularity: 164.646,
        profile_path: '/eVliOvXvpuj3NkdZ9HRw6HLnglg.jpg',
        known_for: [
            {
                adult: false,
                backdrop_path: '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
                id: 385128,
                title: 'Velozes \u0026 Furiosos 9',
                original_language: 'en',
                original_title: 'F9',
                overview:
                    'Dominic Toretto e sua família precisam enfrentar o seu irmão mais novo Jakob, um assassino mortal que está trabalhando com uma antiga inimiga, a cyber-terrorista Cipher.',
                poster_path: '/6TuEPZ3ItlBO8WmH8BmY2aGLhes.jpg',
                media_type: 'movie',
                genre_ids: [28, 12, 80],
                popularity: 47.62,
                release_date: '2021-05-19',
                video: false,
                vote_average: 7.108,
                vote_count: 6883,
            },
            {
                adult: false,
                backdrop_path: '/xdIsccWAECo0YF9aTrPoMFUZiJo.jpg',
                id: 22832,
                title: 'Ninja Assassino',
                original_language: 'en',
                original_title: 'Ninja Assassin',
                overview:
                    'Raizo (Rain) é um dos assassinos mais temidos do mundo. Tirado das ruas na infância, foi treinado pelo clã Ozunu – um grupo secreto cuja existência em si já é considerada uma lenda – para ser um assassino exímio. No entanto, a execução sumária de seu amigo faz com que Raizo volte-se contra o grupo, aguardando o momento da vingança.',
                poster_path: '/h9brQOUyWROaa10HfG7wG2dDSB7.jpg',
                media_type: 'movie',
                genre_ids: [28, 12, 53],
                popularity: 52.821,
                release_date: '2009-09-29',
                video: false,
                vote_average: 6.613,
                vote_count: 1443,
            },
        ],
    },
    {
        adult: false,
        gender: 1,
        id: 54693,
        known_for_department: 'Acting',
        name: 'Emma Stone',
        original_name: 'Emma Stone',
        popularity: 157.427,
        profile_path: '/cZ8a3QvAnj2cgcgVL6g4XaqPzpL.jpg',
        known_for: [
            {
                adult: false,
                backdrop_path: '/kmuSGNlF9mfNHIDOEVEWPj6f3Ak.jpg',
                id: 337404,
                title: 'Cruella',
                original_language: 'en',
                original_title: 'Cruella',
                overview:
                    'Na Londres dos anos 70 em meio à revolução do punk rock, Estella, uma garota inteligente e criativa determinada a fazer um nome para si através de seus designs. Ela faz amizade com uma dupla de jovens ladrões e, juntos, constroem uma vida para si nas ruas de Londres. Um dia, o talento de Estella para a moda chama a atenção da Baronesa Von Hellman, uma lenda fashion que é devastadoramente chique e assustadora. Mas o relacionamento delas desencadeia um curso de eventos e revelações que farão com que Estella abrace seu lado rebelde e se torne a Cruella má, elegante e voltada para a vingança.',
                poster_path: '/rRYNGhcAZlTfIUS7iFoF4H9iDbc.jpg',
                media_type: 'movie',
                genre_ids: [35, 80],
                popularity: 67.062,
                release_date: '2021-05-26',
                video: false,
                vote_average: 8.028,
                vote_count: 8861,
            },
            {
                adult: false,
                backdrop_path: '/sxskOU71CO8LaNX2LOtjYFUtKv7.jpg',
                id: 1930,
                title: 'O Espetacular Homem-Aranha',
                original_language: 'en',
                original_title: 'The Amazing Spider-Man',
                overview:
                    'Peter Parker está tentando saber mais sobre sua origem. Ele encontra uma pasta que pertenceu ao seu pai e quer descobrir por que seus pais desapareceram. Sua busca o leva a Oscorp e ao dr. Curt Connors, que tem como alterego o letal Lagarto.',
                poster_path: '/gxSsFBCFuDhVQMCuIDoZcmHOqlY.jpg',
                media_type: 'movie',
                genre_ids: [28, 12, 878],
                popularity: 73.705,
                release_date: '2012-06-23',
                video: false,
                vote_average: 6.697,
                vote_count: 16732,
            },
            {
                adult: false,
                backdrop_path: '/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg',
                id: 313369,
                title: 'La La Land: Cantando Estações',
                original_language: 'en',
                original_title: 'La La Land',
                overview:
                    'O pianista Sebastian conhece a atriz Mia, e os dois se apaixonam perdidamente. Em busca de oportunidades para suas carreiras na competitiva Los Angeles, os jovens tentam fazer o relacionamento amoroso dar certo, enquanto perseguem fama e sucesso.',
                poster_path: '/AvMietG6xuobpSSdmVnKuTjv4bL.jpg',
                media_type: 'movie',
                genre_ids: [35, 18, 10749, 10402],
                popularity: 60.782,
                release_date: '2016-11-29',
                video: false,
                vote_average: 7.9,
                vote_count: 16069,
            },
        ],
    },
];
