import { Movie } from '../../models/movie';

export const mockTitle = 'Populares';
export const mockMovies: Movie[] = [
    {
        adult: false,
        backdrop_path: '/4woSOUD0equAYzvwhWBHIJDCM88.jpg',
        genre_ids: [28, 27, 53],
        id: 1096197,
        original_language: 'en',
        original_title: 'No Way Up',
        overview:
            'Um grupo de desconhecidos acabam no meio do Oceano Pacífico depois de um acidente aéreo. Presos em uma bolsa de ar, eles devem trabalhar juntos para enfrentar os perigos que os cercam antes que o oxigênio acabe.',
        popularity: 2426.543,
        poster_path: '/ktxq0LYgl41I2DUn49TYIaS9dZR.jpg',
        release_date: '2024-01-18',
        title: 'Desespero Profundo',
        video: false,
        vote_average: 5.78,
        vote_count: 75,
    },
    {
        adult: false,
        backdrop_path: '/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg',
        genre_ids: [28, 53, 10752],
        id: 969492,
        original_language: 'en',
        original_title: 'Land of Bad',
        overview:
            'Uma missão das forças especiais vira um grande desastre e, cercados pelo inimigo em um território remoto nas Filipinas, a única chance de resgate está nas mãos de Reaper (Russel Crowe), um piloto de drone, e Kinney (Liam Hemsworth), um jovem oficial da aeronáutica. Eles têm 48 horas para resgatar os soldados antes que vire um banho de sangue.',
        popularity: 1438.938,
        poster_path: '/cCRAMT530bTcZ4xs6E6pTUoAalE.jpg',
        release_date: '2024-01-25',
        title: 'Zona de Risco',
        video: false,
        vote_average: 7.002,
        vote_count: 224,
    },
    {
        adult: false,
        backdrop_path: '/zCrUFSJKYLtQDpaAIdbNQ50FUpZ.jpg',
        genre_ids: [878, 10749, 35],
        id: 792307,
        original_language: 'en',
        original_title: 'Poor Things',
        overview:
            'A jovem Bella Baxter é trazida de volta à vida pelo cientista Dr. Godwin Baxter. Querendo ver mais do mundo, ela foge com um advogado e viaja pelos continentes. Livre dos preconceitos de sua época, Bella exige igualdade e libertação.',
        popularity: 1484.797,
        poster_path: '/reIqVavL4QESfQIMT5PW8CvRH13.jpg',
        release_date: '2023-12-07',
        title: 'Pobres Criaturas',
        video: false,
        vote_average: 8.091,
        vote_count: 1513,
    },
    {
        adult: false,
        backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
        genre_ids: [35, 10749],
        id: 1072790,
        original_language: 'en',
        original_title: 'Anyone But You',
        overview:
            'Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.',
        popularity: 1067.573,
        poster_path: '/tPx1HEiS5zd9mLvtb52YY66dkEO.jpg',
        release_date: '2023-12-21',
        title: 'Todos Menos Você',
        video: false,
        vote_average: 6.93,
        vote_count: 711,
    },
    {
        adult: false,
        backdrop_path: '/qBQV4i2sjIydDJUKm7pwvpyfy5p.jpg',
        genre_ids: [28, 12, 878],
        id: 693134,
        original_language: 'en',
        original_title: 'Dune: Part Two',
        overview:
            'A jornada de Paul Atreides continua. Ele se une a Chani e aos Fremen em uma guerra de vingança contra aqueles que destruíram sua família. Diante de uma escolha entre o amor de sua vida e o destino do universo, Paul tenta evitar um futuro terrível que só ele pode prever.',
        popularity: 1015.525,
        poster_path: '/opifTi4YVvqMJkDpMCi2mjwE77B.jpg',
        release_date: '2024-02-27',
        title: 'Duna: Parte Dois',
        video: false,
        vote_average: 8.486,
        vote_count: 248,
    },
    {
        adult: false,
        backdrop_path: '/meyhnvssZOPPjud4F1CjOb4snET.jpg',
        genre_ids: [16, 28, 12, 35, 10751],
        id: 940551,
        original_language: 'en',
        original_title: 'Migration',
        overview:
            'A família Mallard está um pouco refém da rotina. Enquanto Mack, o pai, se contenta em manter sua família segura nos arredores de um lago da Nova Inglaterra para sempre, Pam, a mãe, está ansiosa para agitar as coisas e mostrar a seus filhos – o adolescente Dax e a patinha Gwen – o mundo inteiro. Quando uma família de patos migratórios aterrissa em seu lago com histórias emocionantes de lugares distantes, Pam convence Mack a embarcar em uma viagem em família, via Nova York, para a Jamaica tropical.',
        popularity: 993.226,
        poster_path: '/apAIqBHMqjKlId60cj7V32bZIS3.jpg',
        release_date: '2023-12-06',
        title: 'Patos!',
        video: false,
        vote_average: 7.619,
        vote_count: 810,
    },
    {
        adult: false,
        backdrop_path: '/1QuloKG6VhFB94BhjX7VknKsNmZ.jpg',
        genre_ids: [18, 53],
        id: 1026436,
        original_language: 'en',
        original_title: "Miller's Girl",
        overview:
            'Uma jovem escritora talentosa embarca numa odisseia criativa quando o seu professor lhe atribui um projeto que os envolve numa teia cada vez mais complexa.',
        popularity: 432.11,
        poster_path: '/aygFQeDmmtlArzo8epmsOg9mz9f.jpg',
        release_date: '2024-01-18',
        title: "Miller's Girl",
        video: false,
        vote_average: 6.7,
        vote_count: 143,
    },
    {
        adult: false,
        backdrop_path: '/dmiN2rakG9hZW04Xx7mHOoHTOyD.jpg',
        genre_ids: [35],
        id: 673593,
        original_language: 'en',
        original_title: 'Mean Girls',
        overview:
            'A adolescente Cady Heron foi educada na África pelos seus pais cientistas. Quando sua família se muda para o subúrbio, nos Estados Unidos, Cady começa a frequentar a escola pública e recebe uma rápida introdução às leis de popularidade que dividem seus colegas. Sem querer, ela acaba no meio de um grupo de elite de estudantes apelidadas “as poderosas”.',
        popularity: 390.679,
        poster_path: '/vZx6gIkqiZ559w1S8wFHIeKmp7C.jpg',
        release_date: '2024-01-10',
        title: 'Meninas Malvadas',
        video: false,
        vote_average: 6.412,
        vote_count: 205,
    },
];
