import { Actor } from '../../shared/models/actor';
import { Response } from '../../shared/models/response';

export const mockGetPopularActors: Response<Actor> = {
    page: 1,
    results: [
        {
            adult: false,
            gender: 2,
            id: 976,
            known_for_department: 'Acting',
            name: 'Jason Statham',
            original_name: 'Jason Statham',
            popularity: 428.502,
            profile_path: '/lldeQ91GwIVff43JBrpdbAAeYWj.jpg',
            known_for: [
                {
                    adult: false,
                    backdrop_path: '/2uSCHUsmzb6KkQPFSxBQ7bgfJLE.jpg',
                    id: 345940,
                    title: 'Megatubarão',
                    original_language: 'en',
                    original_title: 'The Meg',
                    overview:
                        'Na fossa mais profunda do Oceano Pacífico, a tripulação de um submarino fica presa dentro do local após ser atacada por uma criatura pré-histórica que se achava estar extinta, um tubarão de mais de 20 metros de comprimento, o Megalodon. Para salvá-los, um oceanógrafo chinês contrata Jonas Taylor, um mergulhador especializado em resgates em água profundas que já encontrou com a criatura anteriormente.',
                    poster_path: '/wrJkShDPK4TcV0nHix3HASEmkul.jpg',
                    media_type: 'movie',
                    genre_ids: [28, 878, 27],
                    popularity: 62.654,
                    release_date: '2018-08-09',
                    video: false,
                    vote_average: 6.3,
                    vote_count: 7314,
                },
                {
                    adult: false,
                    backdrop_path: '/kWt1OcPgwO1ssu57wgTKmq38JYw.jpg',
                    id: 4108,
                    title: 'Carga Explosiva',
                    original_language: 'en',
                    original_title: 'The Transporter',
                    overview:
                        'O ex-operador das Forças Especiais Frank Martin vive o que parece ser uma vida tranquila ao longo do Mediterrâneo francês. Na verdade ele é um transportador mercenário levando bens, humanos ou não, de um lugar para outro, sem fazer perguntas sobre que tipo de mercadoria foi contratado para transportar.',
                    poster_path: '/iajTcyco5MEscLp0ue59lVY2WtH.jpg',
                    media_type: 'movie',
                    genre_ids: [28, 80, 53],
                    popularity: 39.506,
                    release_date: '2002-10-02',
                    video: false,
                    vote_average: 6.7,
                    vote_count: 5071,
                },
                {
                    adult: false,
                    backdrop_path: '/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg',
                    id: 337339,
                    title: 'Velozes \u0026 Furiosos 8',
                    original_language: 'en',
                    original_title: 'The Fate of the Furious',
                    overview:
                        'Depois que Brian e Mia se aposentaram, e o resto da equipe foi exonerado, Dom e Letty estão em lua de mel e levam uma vida pacata e completamente normal. Mas a adrenalina do passado volta com tudo quando uma mulher misteriosa faz com que Dom retorne ao mundo do crime e da velocidade.',
                    poster_path: '/38RVo4cX1O7Ia6k9WXcxkxprHm.jpg',
                    media_type: 'movie',
                    genre_ids: [28, 80, 53],
                    popularity: 64.352,
                    release_date: '2017-04-12',
                    video: false,
                    vote_average: 6.881,
                    vote_count: 9952,
                },
            ],
        },
        {
            adult: false,
            gender: 1,
            id: 54693,
            known_for_department: 'Acting',
            name: 'Emma Stone',
            original_name: 'Emma Stone',
            popularity: 277.427,
            profile_path: '/8NwSfyYWIIUE1cI9Xhz92b0w7WD.jpg',
            known_for: [
                {
                    adult: false,
                    backdrop_path: '/kmuSGNlF9mfNHIDOEVEWPj6f3Ak.jpg',
                    id: 337404,
                    title: 'Cruella',
                    original_language: 'en',
                    original_title: 'Cruella',
                    overview:
                        'Na Londres dos anos 70 em meio à revolução do punk rock, Estella, uma garota inteligente e criativa determinada a fazer um nome para si através de seus designs. Ela faz amizade com uma dupla de jovens ladrões e, juntos, constroem uma vida para si nas ruas de Londres. Um dia, o talento de Estella para a moda chama a atenção da Baronesa Von Hellman, uma lenda fashion que é devastadoramente chique e assustadora. Mas o relacionamento delas desencadeia um curso de eventos e revelações que farão com que Estella abrace seu lado rebelde e se torne a Cruella má, elegante e voltada para a vingança.',
                    poster_path: '/rRYNGhcAZlTfIUS7iFoF4H9iDbc.jpg',
                    media_type: 'movie',
                    genre_ids: [35, 80],
                    popularity: 70.996,
                    release_date: '2021-05-26',
                    video: false,
                    vote_average: 8.027,
                    vote_count: 8868,
                },
                {
                    adult: false,
                    backdrop_path: '/sxskOU71CO8LaNX2LOtjYFUtKv7.jpg',
                    id: 1930,
                    title: 'O Espetacular Homem-Aranha',
                    original_language: 'en',
                    original_title: 'The Amazing Spider-Man',
                    overview:
                        'Peter Parker está tentando saber mais sobre sua origem. Ele encontra uma pasta que pertenceu ao seu pai e quer descobrir por que seus pais desapareceram. Sua busca o leva a Oscorp e ao dr. Curt Connors, que tem como alterego o letal Lagarto.',
                    poster_path: '/gxSsFBCFuDhVQMCuIDoZcmHOqlY.jpg',
                    media_type: 'movie',
                    genre_ids: [28, 12, 878],
                    popularity: 75.831,
                    release_date: '2012-06-23',
                    video: false,
                    vote_average: 6.697,
                    vote_count: 16737,
                },
                {
                    adult: false,
                    backdrop_path: '/nofXR1TN1vgGjdfnwGQwFaAWBaY.jpg',
                    id: 313369,
                    title: 'La La Land: Cantando Estações',
                    original_language: 'en',
                    original_title: 'La La Land',
                    overview:
                        'O pianista Sebastian conhece a atriz Mia, e os dois se apaixonam perdidamente. Em busca de oportunidades para suas carreiras na competitiva Los Angeles, os jovens tentam fazer o relacionamento amoroso dar certo, enquanto perseguem fama e sucesso.',
                    poster_path: '/AvMietG6xuobpSSdmVnKuTjv4bL.jpg',
                    media_type: 'movie',
                    genre_ids: [35, 18, 10749, 10402],
                    popularity: 63.836,
                    release_date: '2016-11-29',
                    video: false,
                    vote_average: 7.9,
                    vote_count: 16084,
                },
            ],
        },
        {
            adult: false,
            gender: 1,
            id: 115440,
            known_for_department: 'Acting',
            name: 'Sydney Sweeney',
            original_name: 'Sydney Sweeney',
            popularity: 220.813,
            profile_path: '/qYiaSl0Eb7G3VaxOg8PxExCFwon.jpg',
            known_for: [
                {
                    adult: false,
                    backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
                    id: 1072790,
                    title: 'Todos Menos Você',
                    original_language: 'en',
                    original_title: 'Anyone But You',
                    overview:
                        'Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.',
                    poster_path: '/tPx1HEiS5zd9mLvtb52YY66dkEO.jpg',
                    media_type: 'movie',
                    genre_ids: [35, 10749],
                    popularity: 822.681,
                    release_date: '2023-12-21',
                    video: false,
                    vote_average: 6.999,
                    vote_count: 928,
                },
                {
                    adult: false,
                    backdrop_path: '/3rwszCm4XyBtIWSjbUbgNwJOidu.jpg',
                    id: 645710,
                    title: 'Observadores',
                    original_language: 'en',
                    original_title: 'The Voyeurs',
                    overview:
                        'Depois de se mudarem para um lindo apartamento no centro de Montreal, um jovem casal começa a se interessar cada vez mais pela vida sexual de seus vizinhos excêntricos do outro lado da rua. O que começa como uma curiosidade inocente aos poucos se transforma em uma obsessão doentia, depois que descobrem que um dos vizinhos está traindo o outro. A tentação e o desejo fazem com que suas vidas se enredem de maneiras inesperadas, levando a consequências mortais.',
                    poster_path: '/bOFs0xHCOSTvIUYL0LDd5qcuuDB.jpg',
                    media_type: 'movie',
                    genre_ids: [53],
                    popularity: 47.769,
                    release_date: '2021-08-25',
                    video: false,
                    vote_average: 6.643,
                    vote_count: 771,
                },
            ],
        },
    ],
    total_pages: 165150,
    total_results: 3302994,
};
