import { MovieDetails } from '../../../shared/models/movie-details';
import { Movie } from '../../../shared/models/movie';
import { Response } from '../../../shared/models/response';

export const environment = {
    apiKey: '123456',
};

export const mockMoviesNowPlaing: Response<Movie> = {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/4woSOUD0equAYzvwhWBHIJDCM88.jpg',
            genre_ids: [28, 27, 53],
            id: 1096197,
            original_language: 'en',
            original_title: 'No Way Up',
            overview:
                'Um grupo de desconhecidos acabam no meio do Oceano Pacífico depois de um acidente aéreo. Presos em uma bolsa de ar, eles devem trabalhar juntos para enfrentar os perigos que os cercam antes que o oxigênio acabe.',
            popularity: 2426.543,
            poster_path: '/ktxq0LYgl41I2DUn49TYIaS9dZR.jpg',
            release_date: '2024-01-18',
            title: 'Desespero Profundo',
            video: false,
            vote_average: 5.78,
            vote_count: 75,
        },
        {
            adult: false,
            backdrop_path: '/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg',
            genre_ids: [28, 53, 10752],
            id: 969492,
            original_language: 'en',
            original_title: 'Land of Bad',
            overview:
                'Uma missão das forças especiais vira um grande desastre e, cercados pelo inimigo em um território remoto nas Filipinas, a única chance de resgate está nas mãos de Reaper (Russel Crowe), um piloto de drone, e Kinney (Liam Hemsworth), um jovem oficial da aeronáutica. Eles têm 48 horas para resgatar os soldados antes que vire um banho de sangue.',
            popularity: 1438.938,
            poster_path: '/cCRAMT530bTcZ4xs6E6pTUoAalE.jpg',
            release_date: '2024-01-25',
            title: 'Zona de Risco',
            video: false,
            vote_average: 7.002,
            vote_count: 224,
        },
        {
            adult: false,
            backdrop_path: '/zCrUFSJKYLtQDpaAIdbNQ50FUpZ.jpg',
            genre_ids: [878, 10749, 35],
            id: 792307,
            original_language: 'en',
            original_title: 'Poor Things',
            overview:
                'A jovem Bella Baxter é trazida de volta à vida pelo cientista Dr. Godwin Baxter. Querendo ver mais do mundo, ela foge com um advogado e viaja pelos continentes. Livre dos preconceitos de sua época, Bella exige igualdade e libertação.',
            popularity: 1484.797,
            poster_path: '/reIqVavL4QESfQIMT5PW8CvRH13.jpg',
            release_date: '2023-12-07',
            title: 'Pobres Criaturas',
            video: false,
            vote_average: 8.091,
            vote_count: 1513,
        },
        {
            adult: false,
            backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
            genre_ids: [35, 10749],
            id: 1072790,
            original_language: 'en',
            original_title: 'Anyone But You',
            overview:
                'Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.',
            popularity: 1067.573,
            poster_path: '/tPx1HEiS5zd9mLvtb52YY66dkEO.jpg',
            release_date: '2023-12-21',
            title: 'Todos Menos Você',
            video: false,
            vote_average: 6.93,
            vote_count: 711,
        },
        {
            adult: false,
            backdrop_path: '/qBQV4i2sjIydDJUKm7pwvpyfy5p.jpg',
            genre_ids: [28, 12, 878],
            id: 693134,
            original_language: 'en',
            original_title: 'Dune: Part Two',
            overview:
                'A jornada de Paul Atreides continua. Ele se une a Chani e aos Fremen em uma guerra de vingança contra aqueles que destruíram sua família. Diante de uma escolha entre o amor de sua vida e o destino do universo, Paul tenta evitar um futuro terrível que só ele pode prever.',
            popularity: 1015.525,
            poster_path: '/opifTi4YVvqMJkDpMCi2mjwE77B.jpg',
            release_date: '2024-02-27',
            title: 'Duna: Parte Dois',
            video: false,
            vote_average: 8.486,
            vote_count: 248,
        },
        {
            adult: false,
            backdrop_path: '/meyhnvssZOPPjud4F1CjOb4snET.jpg',
            genre_ids: [16, 28, 12, 35, 10751],
            id: 940551,
            original_language: 'en',
            original_title: 'Migration',
            overview:
                'A família Mallard está um pouco refém da rotina. Enquanto Mack, o pai, se contenta em manter sua família segura nos arredores de um lago da Nova Inglaterra para sempre, Pam, a mãe, está ansiosa para agitar as coisas e mostrar a seus filhos – o adolescente Dax e a patinha Gwen – o mundo inteiro. Quando uma família de patos migratórios aterrissa em seu lago com histórias emocionantes de lugares distantes, Pam convence Mack a embarcar em uma viagem em família, via Nova York, para a Jamaica tropical.',
            popularity: 993.226,
            poster_path: '/apAIqBHMqjKlId60cj7V32bZIS3.jpg',
            release_date: '2023-12-06',
            title: 'Patos!',
            video: false,
            vote_average: 7.619,
            vote_count: 810,
        },
    ],
    total_pages: 46,
    total_results: 906,
};

export const mockMoviesPopular: Response<Movie> = {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/4woSOUD0equAYzvwhWBHIJDCM88.jpg',
            genre_ids: [28, 27, 53],
            id: 1096197,
            original_language: 'en',
            original_title: 'No Way Up',
            overview:
                'Um grupo de desconhecidos acabam no meio do Oceano Pacífico depois de um acidente aéreo. Presos em uma bolsa de ar, eles devem trabalhar juntos para enfrentar os perigos que os cercam antes que o oxigênio acabe.',
            popularity: 2426.543,
            poster_path: '/ktxq0LYgl41I2DUn49TYIaS9dZR.jpg',
            release_date: '2024-01-18',
            title: 'Desespero Profundo',
            video: false,
            vote_average: 5.806,
            vote_count: 80,
        },
        {
            adult: false,
            backdrop_path: '/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg',
            genre_ids: [28, 53, 10752],
            id: 969492,
            original_language: 'en',
            original_title: 'Land of Bad',
            overview:
                'Uma missão das forças especiais vira um grande desastre e, cercados pelo inimigo em um território remoto nas Filipinas, a única chance de resgate está nas mãos de Reaper (Russel Crowe), um piloto de drone, e Kinney (Liam Hemsworth), um jovem oficial da aeronáutica. Eles têm 48 horas para resgatar os soldados antes que vire um banho de sangue.',
            popularity: 1438.938,
            poster_path: '/cCRAMT530bTcZ4xs6E6pTUoAalE.jpg',
            release_date: '2024-01-25',
            title: 'Zona de Risco',
            video: false,
            vote_average: 7.011,
            vote_count: 229,
        },
        {
            adult: false,
            backdrop_path: '/zCrUFSJKYLtQDpaAIdbNQ50FUpZ.jpg',
            genre_ids: [878, 10749, 35],
            id: 792307,
            original_language: 'en',
            original_title: 'Poor Things',
            overview:
                'A jovem Bella Baxter é trazida de volta à vida pelo cientista Dr. Godwin Baxter. Querendo ver mais do mundo, ela foge com um advogado e viaja pelos continentes. Livre dos preconceitos de sua época, Bella exige igualdade e libertação.',
            popularity: 1484.797,
            poster_path: '/reIqVavL4QESfQIMT5PW8CvRH13.jpg',
            release_date: '2023-12-07',
            title: 'Pobres Criaturas',
            video: false,
            vote_average: 8.09,
            vote_count: 1519,
        },
        {
            adult: false,
            backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
            genre_ids: [35, 10749],
            id: 1072790,
            original_language: 'en',
            original_title: 'Anyone But You',
            overview:
                'Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.',
            popularity: 1067.573,
            poster_path: '/tPx1HEiS5zd9mLvtb52YY66dkEO.jpg',
            release_date: '2023-12-21',
            title: 'Todos Menos Você',
            video: false,
            vote_average: 6.934,
            vote_count: 712,
        },
        {
            adult: false,
            backdrop_path: '/qBQV4i2sjIydDJUKm7pwvpyfy5p.jpg',
            genre_ids: [28, 12, 878],
            id: 693134,
            original_language: 'en',
            original_title: 'Dune: Part Two',
            overview:
                'A jornada de Paul Atreides continua. Ele se une a Chani e aos Fremen em uma guerra de vingança contra aqueles que destruíram sua família. Diante de uma escolha entre o amor de sua vida e o destino do universo, Paul tenta evitar um futuro terrível que só ele pode prever.',
            popularity: 1015.525,
            poster_path: '/opifTi4YVvqMJkDpMCi2mjwE77B.jpg',
            release_date: '2024-02-27',
            title: 'Duna: Parte Dois',
            video: false,
            vote_average: 8.494,
            vote_count: 254,
        },
        {
            adult: false,
            backdrop_path: '/meyhnvssZOPPjud4F1CjOb4snET.jpg',
            genre_ids: [16, 28, 12, 35, 10751],
            id: 940551,
            original_language: 'en',
            original_title: 'Migration',
            overview:
                'A família Mallard está um pouco refém da rotina. Enquanto Mack, o pai, se contenta em manter sua família segura nos arredores de um lago da Nova Inglaterra para sempre, Pam, a mãe, está ansiosa para agitar as coisas e mostrar a seus filhos – o adolescente Dax e a patinha Gwen – o mundo inteiro. Quando uma família de patos migratórios aterrissa em seu lago com histórias emocionantes de lugares distantes, Pam convence Mack a embarcar em uma viagem em família, via Nova York, para a Jamaica tropical.',
            popularity: 993.226,
            poster_path: '/apAIqBHMqjKlId60cj7V32bZIS3.jpg',
            release_date: '2023-12-06',
            title: 'Patos!',
            video: false,
            vote_average: 7.619,
            vote_count: 810,
        },
    ],
    total_pages: 42748,
    total_results: 854959,
};

export const mockMoviesTopRated: Response<Movie> = {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
            genre_ids: [18, 80],
            id: 278,
            original_language: 'en',
            original_title: 'The Shawshank Redemption',
            overview:
                'Em 1946, Andy Dufresne, um banqueiro jovem e bem sucedido, tem a sua vida radicalmente modificada ao ser condenado por um crime que nunca cometeu, o homicídio de sua esposa e do amante dela. Ele é mandado para uma prisão que é o pesadelo de qualquer detento, a Penitenciária Estadual de Shawshank, no Maine. Lá ele irá cumprir a pena perpétua. Andy logo será apresentado a Warden Norton, o corrupto e cruel agente penitenciário, que usa a Bíblia como arma de controle e ao Capitão Byron Hadley que trata os internos como animais. Andy faz amizade com Ellis Boyd Redding, um prisioneiro que cumpre pena há 20 anos e controla o mercado negro da instituição.',
            popularity: 128.965,
            poster_path: '/umX3lBhHoTV7Lsci140Yr8VpXyN.jpg',
            release_date: '1994-09-23',
            title: 'Um Sonho de Liberdade',
            video: false,
            vote_average: 8.7,
            vote_count: 25691,
        },
        {
            adult: false,
            backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
            genre_ids: [18, 80],
            id: 238,
            original_language: 'en',
            original_title: 'The Godfather',
            overview:
                'Em 1945, Don Corleone é o chefe de uma mafiosa família italiana de Nova York. Ele costuma apadrinhar várias pessoas, realizando importantes favores para elas, em troca de favores futuros. Com a chegada das drogas, as famílias começam uma disputa pelo promissor mercado. Quando Corleone se recusa a facilitar a entrada dos narcóticos na cidade, não oferecendo ajuda política e policial, sua família começa a sofrer atentados para que mudem de posição. É nessa complicada época que Michael, um herói de guerra nunca envolvido nos negócios da família, vê a necessidade de proteger o seu pai e tudo o que ele construiu ao longo dos anos.',
            popularity: 110.668,
            poster_path: '/oJagOzBu9Rdd9BrciseCm3U3MCU.jpg',
            release_date: '1972-03-14',
            title: 'O Poderoso Chefão',
            video: false,
            vote_average: 8.695,
            vote_count: 19520,
        },
        {
            adult: false,
            backdrop_path: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
            genre_ids: [18, 80],
            id: 240,
            original_language: 'en',
            original_title: 'The Godfather Part II',
            overview:
                'Após a máfia matar sua família, o jovem Vito foge da sua cidade na Sicília e vai para a América. Vito luta para manter sua família. Ele mata Black Hand Fanucci, que exigia dos comerciantes uma parte dos seus ganhos. Com a morte de Fanucci, o poderio de Vito cresce, mas sua família é o que mais importa para ele. Agora baseado no Lago Tahoe, Michael planeja fazer incursões em Las Vegas e Havana instalando negócios ligados ao lazer, mas descobre que aliados como Hyman Roth estão tentando matá-lo.',
            popularity: 66.949,
            poster_path: '/7g6wvsWHxBQujUcSXvZLhdFpDUy.jpg',
            release_date: '1974-12-20',
            title: 'O Poderoso Chefão: Parte II',
            video: false,
            vote_average: 8.6,
            vote_count: 11791,
        },
        {
            adult: false,
            backdrop_path: '/3f92DMBTFqr3wgXpfxzrb0qv8nG.jpg',
            genre_ids: [18, 36, 10752],
            id: 424,
            original_language: 'en',
            original_title: "Schindler's List",
            overview:
                'O alemão Oskar Schindler viu na mão de obra judia uma solução barata e viável para lucrar com negócios durante a guerra. Com sua forte influência dentro do partido nazista, foi fácil conseguir as autorizações e abrir uma fábrica. O que poderia parecer uma atitude de um homem não muito bondoso, transformou-se em um dos maiores casos de amor à vida da História, pois este alemão abdicou de toda sua fortuna para salvar a vida de mais de mil judeus em plena luta contra o extermínio alemão.',
            popularity: 83.493,
            poster_path: '/tagKKnJLK8W5qKJW7Cl2GR2OPCs.jpg',
            release_date: '1993-12-15',
            title: 'A Lista de Schindler',
            video: false,
            vote_average: 8.565,
            vote_count: 15172,
        },
        {
            adult: false,
            backdrop_path: '/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg',
            genre_ids: [16, 10751, 14],
            id: 129,
            original_language: 'ja',
            original_title: '千と千尋の神隠し',
            overview:
                'Chihiro e seus pais estão se mudando para uma cidade diferente. A caminho da nova casa, o pai decide pegar um atalho. Eles se deparam com uma mesa repleta de comida, embora ninguém esteja por perto. Chihiro sente o perigo, mas seus pais começam a comer. Quando anoitece, eles se transformam em porcos. Agora, apenas Chihiro pode salvá-los',
            popularity: 91.458,
            poster_path: '/hhoKhsyJ3hFaxEm5pMdZRiTu2lJ.jpg',
            release_date: '2001-07-20',
            title: 'A Viagem de Chihiro',
            video: false,
            vote_average: 8.539,
            vote_count: 15572,
        },
        {
            adult: false,
            backdrop_path: '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
            genre_ids: [18],
            id: 389,
            original_language: 'en',
            original_title: '12 Angry Men',
            overview:
                'Um jovem porto-riquenho é acusado do brutal crime de ter matado o próprio pai. Quando ele vai a julgamento, doze jurados se reúnem para decidir a sentença, levando em conta que o réu deve ser considerado inocente até que se prove o contrário. Onze dos jurados têm plena certeza de que ele é culpado, e votam pela condenação, mas um jurado acha que é melhor investigar mais para que a sentença seja correta. Para isso ele terá que enfrentar diferentes interpretações dos fatos, e a má vontade dos outros jurados, que só querem ir logo para suas casas.',
            popularity: 68.82,
            poster_path: '/q8RGf4SbVCObCySZ4PIGsn5wFm6.jpg',
            release_date: '1957-04-10',
            title: '12 Homens e uma Sentença',
            video: false,
            vote_average: 8.538,
            vote_count: 8089,
        },
    ],
    total_pages: 461,
    total_results: 9204,
};

export const mockMovie: MovieDetails = {
    adult: false,
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    belongs_to_collection: {
        id: 230,
        name: 'O Poderoso Chefão: Coleção',
        poster_path: '/s4i9pFeUj4gSJaA487kjq9ePJrR.jpg',
        backdrop_path: '/mDMCET9Ens5ANvZAWRpluBsMAtS.jpg',
    },
    budget: 6000000,
    genres: [
        {
            id: 18,
            name: 'Drama',
        },
    ],
    homepage: '',
    id: 238,
    imdb_id: 'tt0068646',
    original_language: 'en',
    original_title: 'The Godfather',
    overview:
        'Em 1945, Don Corleone é o chefe de uma mafiosa família italiana de Nova York. Ele costuma apadrinhar várias pessoas, realizando importantes favores para elas, em troca de favores futuros. Com a chegada das drogas, as famílias começam uma disputa pelo promissor mercado. Quando Corleone se recusa a facilitar a entrada dos narcóticos na cidade, não oferecendo ajuda política e policial, sua família começa a sofrer atentados para que mudem de posição. É nessa complicada época que Michael, um herói de guerra nunca envolvido nos negócios da família, vê a necessidade de proteger o seu pai e tudo o que ele construiu ao longo dos anos.',
    popularity: 110.668,
    poster_path: '/oJagOzBu9Rdd9BrciseCm3U3MCU.jpg',
    production_companies: [
        {
            id: 4,
            logo_path: '/gz66EfNoYPqHTYI4q9UEN4CbHRc.png',
            name: 'Paramount',
            origin_country: 'US',
        },
    ],
    production_countries: [
        {
            iso_3166_1: 'US',
            name: 'United States of America',
        },
    ],
    release_date: '1972-03-14',
    revenue: 245066411,
    runtime: 175,
    spoken_languages: [
        {
            english_name: 'English',
            iso_639_1: 'en',
            name: 'English',
        },
    ],
    status: 'Released',
    tagline: 'Uma oferta que você não vai poder recusar.',
    title: 'O Poderoso Chefão',
    video: false,
    vote_average: 8.695,
    vote_count: 19520,
    credits: {
        cast: [
            {
                adult: false,
                gender: 2,
                id: 3084,
                known_for_department: 'Acting',
                name: 'Marlon Brando',
                original_name: 'Marlon Brando',
                popularity: 21.017,
                profile_path: '/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg',
                cast_id: 146,
                character: 'Don Vito Corleone',
                credit_id: '6489aa85e2726001072483a9',
                order: 0,
            },
        ],
        crew: [
            {
                adult: false,
                gender: 2,
                id: 154,
                known_for_department: 'Editing',
                name: 'Walter Murch',
                original_name: 'Walter Murch',
                popularity: 12.49,
                profile_path: '/kQh7U7kRLF9NKEMpxiGjZEIu0o3.jpg',
                credit_id: '62bd43fb63d9370092ba09da',
                department: 'Crew',
                job: 'Post Production Consulting',
            },
        ],
    },
    videos: {
        results: [
            {
                iso_639_1: 'pt',
                iso_3166_1: 'BR',
                name: 'O Poderoso Chefão | Aniversário de 50 Anos | Trailer Oficial | Paramount Pictures Brasil',
                key: '0v6MO0EB7UY',
                site: 'YouTube',
                size: 1080,
                type: 'Trailer',
                official: true,
                published_at: '2022-01-13T14:03:27.000Z',
                id: '623a98c2e942be00877e6683',
            },
        ],
    },
    release_dates: {
        results: [
            {
                iso_3166_1: 'AR',
                release_dates: [
                    {
                        certification: '',
                        descriptors: [],
                        iso_639_1: '',
                        note: '',
                        release_date: '2011-11-24T00:00:00.000Z',
                        type: 3,
                    },
                ],
            },
        ],
    },
};

export const mockSearch: Response<Movie> = {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/8UERCtJeV1nhnZZXvdWeg8WlYhW.jpg',
            id: 280,
            title: 'O Exterminador do Futuro 2: O Julgamento Final',
            original_language: 'en',
            original_title: 'Terminator 2: Judgment Day',
            overview:
                'O jovem John Connor é a chave para a vitória da civilização sobre uma rebelião de robôs do futuro. No entanto, ele torna-se alvo de T-1000, um exterminador que pode assumir a forma que desejar e que foi enviado do futuro para matá-lo. Outro exterminador, o renovado T-800, também é enviado de volta ao passado para proteger o garoto. Quando John e sua mãe embarcam na fuga com T-800, o menino cria um vínculo forte e inesperado com o robô.',
            poster_path: '/l5uPlrjcVSI3z3duYeyRAP2E2D0.jpg',
            media_type: 'movie',
            genre_ids: [28, 53, 878],
            popularity: 69.475,
            release_date: '1991-07-03',
            video: false,
            vote_average: 8.11,
            vote_count: 12181,
        },
        {
            adult: false,
            backdrop_path: '/6dpnthrofbqWmvapUyvqCrkdHG.jpg',
            id: 218,
            title: 'O Exterminador do Futuro',
            original_language: 'en',
            original_title: 'The Terminator',
            overview:
                'Em um futuro próximo, a guerra entre humanos e máquinas foi iniciada. Com a tecnologia a seu dispor, um plano inusitado é arquitetado pelas máquinas ao enviar para o passado um andróide com a missão de matar a mãe daquele que viria a se transformar num líder e seu pior inimigo. Contudo, os humanos também conseguem enviar seu representante para proteger a mulher e tentar garantir o futuro da humanidade.',
            poster_path: '/fo4SSoNT1ASI4JP7dOLrosWNWKa.jpg',
            media_type: 'movie',
            genre_ids: [28, 53, 878],
            popularity: 74.649,
            release_date: '1984-10-26',
            video: false,
            vote_average: 7.655,
            vote_count: 12279,
        },
        {
            adult: false,
            backdrop_path: '/fctQU5MoXgJ5pNMljFzlEFXwfSu.jpg',
            id: 127585,
            title: 'X-Men: Dias de um Futuro Esquecido',
            original_language: 'en',
            original_title: 'X-Men: Days of Future Past',
            overview:
                'O conjunto definitivo dos X-Men luta uma guerra pela sobrevivência da espécie em dois períodos de tempo enquanto unem forças com seus eus mais jovens em uma batalha épica que deve mudar o passado – para salvar nosso futuro.',
            poster_path: '/bUm0nSsTA6kfFfZHgNbNFisVe7M.jpg',
            media_type: 'movie',
            genre_ids: [28, 12, 878],
            popularity: 67.845,
            release_date: '2014-05-15',
            video: false,
            vote_average: 7.525,
            vote_count: 14716,
        },
        {
            adult: false,
            backdrop_path: '/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg',
            id: 105,
            title: 'De Volta para o Futuro',
            original_language: 'en',
            original_title: 'Back to the Future',
            overview:
                'Marty McFly, um típico adolescente americano dos anos 80, acidentalmente é enviado de volta ao ano de 1955 em um carro modificado para ser uma máquino do tempo, inventada por um cientista louco. Durante sua fantástica e maluca viagem no tempo, McFly tem que fazer com que seus futuros pais se encontrem e se apaixonem, para que assim ele possa ir de volta para o futuro.',
            poster_path: '/4BTW7PyEYFUFlNpuSeS9hAbpk9P.jpg',
            media_type: 'movie',
            genre_ids: [12, 35, 878],
            popularity: 63.461,
            release_date: '1985-07-03',
            video: false,
            vote_average: 8.317,
            vote_count: 19035,
        },
        {
            adult: false,
            backdrop_path: '/g4a5YLWwi6OCp8TcvxsUNrXMbN5.jpg',
            id: 87101,
            title: 'O Exterminador do Futuro: Gênesis',
            original_language: 'en',
            original_title: 'Terminator Genisys',
            overview:
                'John Connor, líder da resistência humana contra Skynet, envia Kyle Reese de volta a 1984 para proteger sua mãe, Sarah. Porém, Reese se surpreende ao encontrá-la com um exterminador que age como seu protetor, e descobre que o passado foi alterado.',
            poster_path: '/3bsLapI6DxME6niIb74aSD71DRH.jpg',
            media_type: 'movie',
            genre_ids: [878, 28, 53, 12],
            popularity: 96.198,
            release_date: '2015-06-23',
            video: false,
            vote_average: 5.9,
            vote_count: 8059,
        },
        {
            adult: false,
            backdrop_path: '/gTRXgigmgKpeJjW07iq686HZyBD.jpg',
            id: 9323,
            title: 'Ghost in the Shell: O Fantasma do Futuro',
            original_language: 'ja',
            original_title: 'GHOST IN THE SHELL',
            overview:
                'Major Motoko Kusanagi, uma ciborgue do Setor de Segurança Pública 9, recebe a missão de capturar um hacker que está dominando a mente de humanos aperfeiçoados por computador. Mas ela acaba se envolvendo em uma trama de conspirações, que atinge interesses da alta cópula da política.',
            poster_path: '/4YgDy47HKxcSwUPQWrg0J39lEZA.jpg',
            media_type: 'movie',
            genre_ids: [28, 16, 878],
            popularity: 42.817,
            release_date: '1995-11-18',
            video: false,
            vote_average: 7.927,
            vote_count: 3171,
        },
    ],
    total_pages: 24,
    total_results: 467,
};
